### ISSUE TITLE
Where can I find ngx-draggable-dom.scss?

### ISSUE THREAD

**Issue by mariusbolik** [bmartinson/ngx-draggable-dom#35]
The Readme says to include the ngx-draggable-dom.scss in the project, but I cannot find the file.

**Comment by bmartinson** [comment]
Hi there, @mariusbolik - looks like the most recent versions were missing the configuration in `ng-package.json`. Please update to v2.5.2+ and you can import the pre-built scss file from `node_modules/ngx-draggable-dom/styles/ngx-draggable-dom.scss`
