### ISSUE TITLE
ERROR InternalError: too much recursion @ get target ngx-draggable-dom.js:127

### ISSUE THREAD

**Issue by timothywalter** [bmartinson/ngx-draggable-dom#9]
https://github.com/bmartinson/ngx-draggable-dom/blob/a4109249a378578cd0d702bd97e0d51407ba0226/projects/ngx-draggable-dom/src/lib/events/ngx-draggable-dom-move-event.ts#L18

No time to make a PR, but the fix would be to return this._target

**Comment by bmartinson** [comment]
Woof, what a painful typo there! Thank you for pointing this out, @timothywalter. I'll get a release out today to rectify this. Sorry about the delay in reacting to this!

**Comment by bmartinson** [comment]
This is resolved in [v2.1.6](https://github.com/bmartinson/ngx-draggable-dom/releases/tag/2.1.6), available now! Thank you again for reporting this issue and once again, I'm so sorry that I overlooked it's submission for so long!
